# Default values for wisp-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: competemcgill/wisp-ui
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "wisp-ui"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 30m
    memory: 50Mi
  requests:
    cpu: 30m
    memory: 50Mi
