name: Build, Tag, Publish and Deploy to GKE

on:
  push:
    branches:
      - dev

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }} 
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wisp-prod
  GKE_ZONE: northamerica-northeast1-c
  IMAGE: wisp-ui

jobs:
  setup-build-tag-publish-deploy:
    name: Setup, Build, Tag, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    # Checkout Commit
    - name: Checkout
      uses: actions/checkout@v2

      # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$DOCKER_ORGANIZATION"/"$IMAGE":dev-$(echo ${GITHUB_SHA} | cut -c1-8) \
        --build-arg VUE_APP_WISP_API_URL=https://dev.api.wisp.training .
    
    # Tag the Docker image
    - name: Tag
      run: |
        docker tag "$DOCKER_ORGANIZATION"/"$IMAGE":dev-$(echo ${GITHUB_SHA} | cut -c1-8) "$DOCKER_ORGANIZATION"/"$IMAGE":dev-latest

    # Push the Docker image to Dockerhub
    - name: Publish
      run: |
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD 
        docker push $DOCKER_ORGANIZATION/$IMAGE
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl -n dev set image deploy/$IMAGE $IMAGE=$DOCKER_ORGANIZATION/$IMAGE:dev-$(echo ${GITHUB_SHA} | cut -c1-8)