name: Build, Tag, and Publish to DockerHub

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }} 
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wisp-prod
  GKE_ZONE: northamerica-northeast1-c
  IMAGE: wisp-ui

jobs:
  setup-build-tag-publish:
    name: Setup, Build, Tag, and Publish
    runs-on: ubuntu-latest
    steps:

    # Checkout Commit
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$DOCKER_ORGANIZATION"/"$IMAGE":$(echo ${GITHUB_SHA} | cut -c1-8) .
    
    # Tag the Docker image
    - name: Tag
      run: |
        docker tag "$DOCKER_ORGANIZATION"/"$IMAGE":$(echo ${GITHUB_SHA} | cut -c1-8) "$DOCKER_ORGANIZATION"/"$IMAGE":latest

    # Push the Docker image to Dockerhub
    - name: Publish
      run: |
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD 
        docker push $DOCKER_ORGANIZATION/$IMAGE
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    # Install helm for use in pipeline
    - name: Install helm
      run: |
        wget -q -O get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Deploy to GKE cluster using helm
    - name: Deploy
      run: |-
        helm upgrade --atomic --install prod-problems ./chart/wisp-problems/ --namespace prod --set image.tag=$(echo ${GITHUB_SHA} | cut -c1-8) --set replicaCount=2